"""create project table

Revision ID: 1d63282ff81a
Revises: 
Create Date: 2026-07-07 19:57:26.868261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1d63282ff81a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_num', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('finished_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'in-progress', 'complete', 'blocked', 'deferred', 'archived', name='status'), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_serial_num_active', 'project', ['serial_num'], unique=True, sqlite_where=sa.text('deleted = false'))
    op.create_index('ix_project_title_active', 'project', ['title'], unique=True, sqlite_where=sa.text('deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_title_active', table_name='project', sqlite_where=sa.text('deleted = false'))
    op.drop_index('ix_project_serial_num_active', table_name='project', sqlite_where=sa.text('deleted = false'))
    op.drop_table('project')
    # ### end Alembic commands ###
