"""create group_task table

Revision ID: afe6a76d4435
Revises: 1d63282ff81a
Create Date: 2026-07-09 10:04:55.231934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'afe6a76d4435'
down_revision: Union[str, Sequence[str], None] = '1d63282ff81a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('serial_num', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('finished_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'in-progress', 'complete', 'blocked', 'deferred', 'archived', name='status'), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_group_task_project_id', 'group_task', ['project_id'], unique=False)
    op.create_index('ix_group_task_project_serial_num_active', 'group_task', ['project_id', 'serial_num'], unique=True, sqlite_where=sa.text('deleted = false'))
    op.create_index('ix_group_task_project_title_active', 'group_task', ['project_id', 'title'], unique=True, sqlite_where=sa.text('deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_group_task_project_title_active', table_name='group_task', sqlite_where=sa.text('deleted = false'))
    op.drop_index('ix_group_task_project_serial_num_active', table_name='group_task', sqlite_where=sa.text('deleted = false'))
    op.drop_index('ix_group_task_project_id', table_name='group_task')
    op.drop_table('group_task')
    # ### end Alembic commands ###
